apiVersion: v2
name: argocd-vs-fluxcd-application
description: A Helm chart for iits-tech OTC presentations
type: application
version: 1.0.0
appVersion: "1.0.2"

dependencies:
  - name: redis
    version: 15.3.0
    repository: https://charts.bitnami.com/bitnami
